Web/SoccerCoach.Web/Controllers/CoachController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Services.Data.Coach;
    using SoccerCoach.Web.ViewModels.Coaches;

    public class CoachController : BaseController
    {
        private readonly ICoachesService coachesService;

        public CoachController(ICoachesService coachesService)
        {
            this.coachesService = coachesService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var viewModel = await this.coachesService.GetAllCoachesAsync<CoachViewModel>();

            return this.View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var viewModel = await this.coachesService.GetCoachById(id);

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Views/Coach/All.cshtml
@model ICollection<SoccerCoach.Web.ViewModels.Coaches.CoachViewModel>
@using SoccerCoach.Common
@{
    this.ViewData["Title"] = "Coaches";
}

<div class="container col-12 d-inline-flex">
    @foreach (var coach in Model)
    {
        <div class="card border-dark col-md-4 game-card mt-2">
            <div class="card-body">              
                <ul class="list-group mt-1 border-danger">
                    <li class="list-group-item bg-dark text-colorise">@coach.Name</li>                   
                    <li class="list-group-item">Workouts: @coach.CoachWorkoutsCount</li>
                    <li class="list-group-item">Courses: @coach.CoursesCount</li>
                        <a asp-controller="Coach" asp-action="Details" asp-route-id="@coach.Id" class="btn orangebackground font-weight-bold" role="button">Details</a>
                </ul>
            </div>
        </div>
    }
</div> 

Web/SoccerCoach.Web/Views/Coach/CreateCourse.cshtml
@model CreateCourseInputModel
@using SoccerCoach.Web.ViewModels.Courses
@using SoccerCoach.Data.Models.Enums
@{
    ViewData["Title"] = "Create";
}

<div class="form container">
    <div class="d-flex justify-content-center">
        <div class="row">
            <div class="col-lg-12">
                <h2>Add Course</h2>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="post" class="text-center border border-light p-5" enctype="multipart/form-data">
                <div class="form-row mb-4">
                    <div class="col">
                        <label asp-for="Name" class="font-weight-bold"></label>
                        <input asp-for="Name" class="form-control">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col">
                        <label asp-for="PositionName" class="font-weight-bold"></label>
                        <select asp-for="PositionName" class="form-control" asp-items="@Html.GetEnumSelectList<PositionName>()"></select>
                        <span asp-validation-for="PositionName" class="text-danger"></span>
                    </div>
                </div>

                <div class="col my-3">
                    <label asp-for="StartDate"  class="font-weight-bold"></label>
                    <input asp-for="StartDate"  class="form form-control-file" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="col my-3">
                    <label asp-for="EndDate" class="font-weight-bold"></label>
                    <input asp-for="EndDate" class="form form-control-file" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>               
                <div class="col my-3">
                    <label asp-for="Description" class="font-weight-bold"></label>
                    <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <hr />
                <button class="btn btn-info btn-lg my-1" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

Web/SoccerCoach.Web/Views/Coach/Details.cshtml
@model SoccerCoach.Web.ViewModels.Coaches.CoachViewModel
@using SoccerCoach.Common
@{
    this.ViewData["Title"] = Model.Name + " Profile";
}
<hr />
<div class="row">
    <div class="col">
        <ul class="list-group mr-lg-5 font-weight-bold">
            <li class="list-group-item orangebackground"><h4>@Model.Name</h4></li>
            <li class="list-group-item">Experience: @Model.Experience years</li>
            <li class="list-group-item">Phone: +@Model.Phone</li>
            <li class="list-group-item">Email: @Model.Email</li>
            <li class="list-group-item">Workouts added: @Model.CoachWorkoutsCount</li>
            <li class="list-group-item">Courses added: @Model.CoursesCount</li>
            <li class="list-group-item">Description:<br> @Model.Description</li>
        </ul>
    </div>
    <div>
        @if (this.User.Identity.IsAuthenticated)
        {
            <ul class="item-rating">
                <h4>Rate this coach:</h4>
                @for (int i = 1; i <= 5; i++)
                {
                    if (i <= Model.AverageVote)
                    {
                        <li class="star-fill" data-vote="@i"><i class="fas fa-star"></i></li>
                    }
                    else
                    {
                        <li class="star-empty" data-vote="@i"><i class="fas fa-star"></i></li>
                    }
                }
                <li><span id="averageVoteValue">@Model.AverageVote.ToString("0.0")</span><span> / 5</span> </li>
            </ul>
        }
    </div>
</div>

<hr />
<form method="post" id="antiForgeryForm"></form>
@section Scripts{
    <script>
        $("li[data-vote]").each(function (el) {
            $(this).click(function () {
                var value = $(this).attr("data-vote");
                var coachId = "@Model.Id";
                var antiForgeryToken = $('#antiForgeryForm input[name=__RequestVerificationToken]').val();
                var data = { coachId: coachId, value: parseInt(value) };
                $.ajax({
                    type: "POST",
                    url: "/api/Votes",
                    data: JSON.stringify(data),
                    headers: {
                        'X-CSRF-TOKEN': antiForgeryToken
                    },
                    success: function (data) {
                        $('#averageVoteValue').html(data.averageVote.toFixed(1));

                        var stars = Array.from($(".fa-star"));
                        for (var i = 0; i < stars.length; i++) {

                            if (i < Math.floor(data.averageVote)) {
                                stars[i].parentNode.classList.remove('star-empty');
                                stars[i].parentNode.classList.add('star-fill');
                            } else {
                                stars[i].parentNode.classList.remove('star-fill');
                                stars[i].parentNode.classList.add('star-empty');
                            }
                        }
                    },
                    contentType: 'application/json',
                });
            })
        });
    </script>
}