Web/SoccerCoach.Web/Controllers/CoachController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Services.Data.Coach;
    using SoccerCoach.Web.ViewModels.Coaches;

    public class CoachController : BaseController
    {
        private readonly ICoachesService coachesService;

        public CoachController(ICoachesService coachesService)
        {
            this.coachesService = coachesService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var viewModel = await this.coachesService.GetAllCoachesAsync<CoachViewModel>();

            return this.View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var viewModel = await this.coachesService.GetCoachById(id);

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Controllers/CourseController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Common;
    using SoccerCoach.Data.Models;
    using SoccerCoach.Services.Data.Coach;
    using SoccerCoach.Services.Data.Course;
    using SoccerCoach.Web.ViewModels.Coaches;
    using SoccerCoach.Web.ViewModels.Courses;

    public class CourseController : BaseController
    {
        private readonly ICoachesService coachesService;
        private readonly ICoursesService coursesService;
        private readonly UserManager<ApplicationUser> userManager;

        public CourseController(
            ICoachesService coachesService,
            ICoursesService coursesService,
            UserManager<ApplicationUser> userManager)
        {
            this.coachesService = coachesService;
            this.coursesService = coursesService;
            this.userManager = userManager;
        }

        [Authorize(Roles = "Coach")]
        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreateCourseInputModel();
            return this.View(viewModel);
        }

        [Authorize(Roles = "Coach")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.coursesService.CreateCourseAsync(input, user.Id);

            return this.RedirectToAction("All");
        }

        [HttpGet]
        public async Task<IActionResult> All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var userId = user != null ? user.Id : string.Empty;

            const int ItemsPerPage = 9;
            var viewModel = new CoursesListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                CoursesCount = this.coursesService.GetCount(),
                Courses = await this.coursesService.GetAll(userId, id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.ClientRoleName)]
        [HttpGet]
        public async Task<IActionResult> ApplyToCourse(string id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var result = await this.coursesService.AddClientToCourse(id, user.Id);

            if (result == "created")
            {
                this.TempData["SuccessMessage"] = GlobalConstants.SuccessfullyAppliedToCourse;
                return this.RedirectToAction("SuccessfullyAdded");
            }

            return this.RedirectToAction("All");
        }

        [HttpGet]
        public IActionResult SuccessfullyAdded()
        {
            return this.View();
        }
    }
}

Web/SoccerCoach.Web/Controllers/PlayerController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Services.Data;

    public class PlayerController : BaseController
    {
        private readonly IPlayersService playersService;

        public PlayerController(IPlayersService playersService)
        {
            this.playersService = playersService;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = await this.playersService.GetAllPlayersAsync<PlayerViewModel>();

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Controllers/WorkoutController.cs
    namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Data.Models;
    using SoccerCoach.Services.Data.Coach;
    using SoccerCoach.Services.Data.Workout;
    using SoccerCoach.Web.ViewModels.Workouts;

    public class WorkoutController : BaseController
    {
        public const int ItemsPerPage = 12;

        private readonly IWorkoutsService workoutsService;
        private readonly UserManager<ApplicationUser> userManager;

        public WorkoutController(
            IWorkoutsService workoutsService,
            UserManager<ApplicationUser> userManager)
        {
            this.workoutsService = workoutsService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult All(SearchWorkoutInputModel inputModel, int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var result = this.workoutsService.GetSearchedPositions<WorkoutInListViewModel>(inputModel, id, ItemsPerPage);
            var viewModel = new ListOfWorkoutsViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                WorkoutsCount = result.Count,
                Workouts = result.Workouts,
                Striker = inputModel.Striker,
                Winger = inputModel.Winger,
                Defender = inputModel.Defender,
                Midfielder = inputModel.Midfielder,
                Goalkeeper = inputModel.Goalkeeper,
            };

            return this.View(viewModel);
        }

        [Authorize(Roles = "Coach")]
        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreateWorkoutInputModel();
            return this.View(viewModel);
        }

        [Authorize(Roles = "Coach")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateWorkoutInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            await this.workoutsService.CreateAsync(input, user.Id);

            return this.RedirectToAction("All");
        }

        [HttpGet]
        [Authorize(Roles = "Coach")]
        public IActionResult Edit(string id)
        {
            var result = this.workoutsService.GetWorkoutForEdit(id);

            return this.View(result);
        }

        [HttpPost]
        [Authorize(Roles = "Coach")]
        public async Task<IActionResult> Edit(EditWorkoutViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.workoutsService.EditAsync(input);
            return this.RedirectToAction("All");
        }

        [Authorize(Roles = "Coach")]
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            await this.workoutsService.DeleteAsync(id);
            return this.RedirectToAction("All");
        }

        [HttpGet]
        public IActionResult Watch(string id)
        {
            var workout = this.workoutsService.GetWorkoutById(id);
            var viewModel = new WatchViewModel()
            {
                WorkoutName = workout.Name,
                VideoUrl = workout.VideoUrl,
            };

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Views/Shared/_Layout.cshtml
@using SoccerCoach.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link href="~/css/custom.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                         @if (!User.Identity.IsAuthenticated)  
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="All">Home</a>
                            </li>
                            <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="All">Workouts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Coach" asp-action="All">Coaches</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="All">Courses</a>
                            </li>
                             @if (User.IsInRole("Coach"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Create">Add Workout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Create">Add Course</a>
                                </li>
                            }
                            @if (User.IsInRole("Client"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="WorkoutsList">Your Workout List</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/ChooseRegisterType.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/SoccerCoach.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav> 