Web/SoccerCoach.Web/Controllers/PlayerController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Services.Data;

    public class PlayerController : BaseController
    {
        private readonly IPlayersService playersService;

        public PlayerController(IPlayersService playersService)
        {
            this.playersService = playersService;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = await this.playersService.GetAllPlayersAsync<PlayerViewModel>();

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Controllers/PlayersController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Services.Data;

    public class PlayersController : BaseController
    {
        private readonly IPlayersService playersService;

        public PlayersController(IPlayersService playersService)
        {
            this.playersService = playersService;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = await this.playersService.GetAllPlayersAsync();

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Controllers/PositionController.cs
namespace SoccerCoach.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerCoach.Services.Data;

    public class PositionController : BaseController
    {
        private readonly IPositionsService positionsService;

        public PositionController(IPositionsService positionsService)
        {
            this.positionsService = positionsService;
        }

        public async Task<IActionResult> Position(string id)
        {
            var viewModel = await this.positionsService.GetPlayerAsync(id);

            return this.View(viewModel);
        }
    }
}

Web/SoccerCoach.Web/Views/Player/All.cshtml
@using SoccerCoach.Common
@{
    this.ViewData["Title"] = "Home Page";
}
@using SoccerCoach.Data.Models.Enums
@model ICollection<SoccerCoach.Web.Controllers.PlayerViewModel>

<div class="text-center">
    <h1 class="display-3">SOCCER COACH</h1>
    <div>
        <span class="display-4 text-break text-">
            Choose your role
        </span>
    </div>
    <div class="d-inline-flex container justify-content-center">
        @foreach (var player in Model)
        {
            <div class="card col-6 col-lg-3 image-resizer">
                <img src="@player.ImageUrl"
                     class="card-img-top img-fluid card-image">
                <div class="card-body">                    
                    <h2 class="">@player.Name</h2>
                    <h5>Position:</h5>
                     <a asp-controller="Position" asp-action="Position" asp-route-id="@player.Id" class="btn btn-outline-warning" role="button">@Html.DisplayFor(model => player.PositionName)</a>
                    <ul class="list-group mt-1 border-danger">
                        <li class="list-group-item">Team Name:<br> @player.TeamName</li>
                        <li class="list-group-item">Experience: @player.Experience</li>
                        <li class="list-group-item">Trophies: @player.Trophies</li>
                        <li class="list-group-item">Height: @player.Height</li>
                        <li class="list-group-item">Weight: @player.Weight</li>
                    </ul>                    
                </div>
            </div>
        }
    </div>
</div> 